name: Weekly Database Update

on:
  schedule:
    - cron: "0 0 * * 0"  # Run every Sunday at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.x

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('lubridate', 'httr', 'purrr', 'jsonlite', 'readr'))"

      - name: Install libcurl for httr (if not available)
        run: |
          if (!requireNamespace("httr", quietly = TRUE)) {
            install.packages("httr", dependencies = TRUE)
          }

      - name: Run R script
        run: Rscript update-database.R
