name: Weekly Database Update

on:
  schedule:
    - cron: "0 0 * * 0"  # Run every Sunday at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.x

<<<<<<< HEAD
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('lubridate', 'purrr', 'jsonlite', 'readr'))"
          Rscript -e "remotes::install_version('httr', version = '1.4.2')"
=======
      - name: Install Dependencies
        run: |
          Rscript -e "install.packages(c('lubridate', 'httr', 'purrr', 'jsonlite', 'readr'))"
>>>>>>> parent of 9bb9cd1 (renv update)

      - name: Run R script
        run: Rscript update-database.R
