name: Weekly Database Update

on:
  schedule:
    - cron: "0 0 * * 0"  # Run every Sunday at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.x

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v1

      - name: Run R script
        run: |
          Rscript -e "install.packages('MASS', version = '7.3-59')"
          Rscript update-database.R

