name: Weekly Database Update

on:
  schedule:
    - cron: "0 0 * * 0"  # Run every Sunday at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.x
          
      - name: Set CRAN Mirror
        run: Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org"))'


      - name: Restore R Environment with renv
        run: Rscript -e 'renv::restore()'

      - name: Run R script
        run: Rscript update-database.R
